global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus próprio
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Aplicação backend
  - job_name: 'backend-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (se disponível)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Tempo
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

# Configuração para remote write (opcional)
# remote_write:
#   - url: "http://prometheus-remote-write-endpoint"

# Configuração para alertas (opcional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
